### ISSUE TITLE
deepfm模型的fm实现和FM模型不一样

### ISSUE THREAD

**Issue by Jasperty** [ZiyaoGeng/RecLearn#18]
两部分的FM输入不一样：
FM模型的实现以连续特征+离散one-hot特征作为输入，再映射隐向量，计算一阶二阶，符合论文；
deepFM模型的FM实现以连续特征+离散embedding特征作为输入，再次映射隐向量计算。（并且没有和deep部分共享隐向量）
此处是否有误？

**Comment by Jasperty** [comment]
另外，one-hot特征可能存在大量0特征，使用整个的矩阵乘法会把0的部分也计算进去，是否用field index映射的方法更加高效呢？每个field所对应的特征直接取对应的w和隐向量进行计算

**Comment by ZiyaoGeng** [comment]
目前已更新，感谢指出
