### ISSUE TITLE
AttRec 資料集中正負樣本劃分的問題

### ISSUE THREAD

**Issue by R7788380** [ZiyaoGeng/RecLearn#21]
作者您好，AttRec 的資料處理程式碼中，依照您 README.md 的敘述，大於等於 trans_score 作為正樣本，小於 trans_score 作為負樣本，用戶沒看過的電影也會被當成負樣本
```
    # implicit dataset
    data_df.loc[data_df.label < trans_score, 'label'] = 0
    data_df.loc[data_df.label >= trans_score, 'label'] = 1
```

但是我在看程式碼時，發現用戶評分小於 trans_score 的電影卻會被分為正樣本。我發現問題在以下程式碼：

```
        pos_list = df['item_id'].tolist()
        def gen_neg():
            neg = pos_list[0]
            while neg in pos_list:
                neg = random.randint(1, item_id_max)
                return neg
```
使用 gen_neg 生成負樣本時，只有檢查 neg 是否在 pos_list 裡，但是 pos_list 卻是包含所有的 item_id，沒有是否為正負樣本的判斷，這樣會導致把評分小於 trans_score 的資料被分為正樣本，想請問作者這邊的問題。

**Comment by ZiyaoGeng** [comment]
你好，我经过另一位读者的提醒，我也发现了这个问题，确实是写错了，应该是：
```
data_df = data_df[data_df.label >= trans_score]
```
