### ISSUE TITLE
SASRec 模型中正负样本划分问题

### ISSUE THREAD

**Issue by zhangfangkai** [ZiyaoGeng/RecLearn#22]
作者您好：
在SASRec模型的数据处理文件util.py中，有
# implicit dataset
data_df.loc[data_df.label < 2, 'label'] = 0
data_df.loc[data_df.label >= 2, 'label'] = 1
可以理解为将评分小于2的视为负样本，但是在之后构造训练集和测试集的时候，这个负样本并没有考虑到，还是以用户交互过的物品作为正样本，未交互过的视为负样本。因此这儿根据评分划分正负样本没有意义吧？
不知道我的理解对不对？

**Comment by ZiyaoGeng** [comment]
你好，非常感谢你的建议，没想到在utils.py出现了这个问题，
应该是`data_df = data_df[data_df.label >= trans_score]`
