### ISSUE TITLE
建议数据输入方式使用tfrecords

### ISSUE THREAD

**Issue by abc1239** [ZiyaoGeng/RecLearn#28]
发现代码中都是使用csv、txt、pkl等方式给模型喂数据，虽然学习起来简单，但是却没办法在工业直接复用，工业数据基本都是通过tfrecords方式进行训练。只有经得起大数据量工业验证的代码，才是真正的好代码。

**Comment by ZiyaoGeng** [comment]
感谢您的建议，目前确实也考虑替换输入的方式

**Comment by abc1239** [comment]
如果有需要，我可以提供一些tfrecords格式的工业数据，毕竟开源的数据集大多没有tfrecords格式的

**Comment by huobumingbai** [comment]
这个的确有必要

**Comment by ZiyaoGeng** [comment]
> 如果有需要，我可以提供一些tfrecords格式的工业数据，毕竟开源的数据集大多没有tfrecords格式的

非常感谢，我需要的话，会再向您提出请求。
