### ISSUE TITLE
SASRec模型多头注意力问题

### ISSUE THREAD

**Issue by zzyo-yu** [ZiyaoGeng/RecLearn#37]
代码参数中num_heads参数为1，当我调整为2时间，就会报错：
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  condition [512,200,1], then [1024,200,200], and else [1024,200,200] must be broadcastable
	 [[node sas_rec_4/encoder_layer_8/multi_head_attention_8/SelectV2 (defined at <ipython-input-8-d12383f007cb>:38) ]]
	 [[div_no_nan/ReadVariableOp_1/_92]]
  (1) Invalid argument:  condition [512,200,1], then [1024,200,200], and else [1024,200,200] must be broadcastable
	 [[node sas_rec_4/encoder_layer_8/multi_head_attention_8/SelectV2 (defined at <ipython-input-8-d12383f007cb>:38) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_train_function_21054]

**Comment by yuyinxiao** [comment]
这里代码感觉有问题，对q k v都进行了reshape处理，然而并没有对mask进行处理

**Comment by MarkoLING** [comment]
请问问题解决了吗

**Comment by ZiyaoGeng** [comment]
这个确实有问题，在master分支忘了改，在reclearn分支中已经改正了，可以看下，https://github.com/ZiyaoGeng/Recommender-System-with-TF2.0/blob/reclearn/reclearn/models/matching/sasrec.py。
