### ISSUE TITLE
BN的疑问

### ISSUE THREAD

**Issue by cyjj** [ZiyaoGeng/RecLearn#40]
https://github.com/ZiyaoGeng/Recommender-System-with-TF2.0/blob/2aedb66620db9a69fb0616a1832c9081835149e8/NFM/model.py#L56

`bn_use`这个参数看上面的说明是觉得是否使用bn层的，那么这里是不是应该写成
`if self.bn_use:
    x = self.bn(x, training=training)`
不知道我是不是理解错这里的意思的了

**Comment by ZiyaoGeng** [comment]
我看了一下，确实写错了。不过上述需要将training去掉，tf2.x中training不需要指定，默认train中为True，而推断中为False，采用的是移动平均。

**Comment by cyjj** [comment]
确实是的，感谢分享~
