### ISSUE TITLE
NFM/model/call中有一个未定义的变量

### ISSUE THREAD

**Issue by wangych6** [ZiyaoGeng/RecLearn#46]
作者您好： NFM/model/call 54行左右Concat里：x = tf.concat([dense_inputs, sparse_embed], axis=-1)  这里sparse_embed前面并没有定义啊，函数参数列表也没有，是怎么跑通的？

**Comment by ZiyaoGeng** [comment]
前面不是有么？

**Comment by Schnappipity** [comment]
> 前面不是有么？

哦哦哦不好意思， 说反了，saprse_embed是有的， 但是dense_inputs是没有的
