### ISSUE TITLE
Deemfm中关于fm的问题

### ISSUE THREAD

**Issue by yanduoduan** [ZiyaoGeng/RecLearn#66]
大佬您好，刚入门推荐，阅读您的代码有一些地方不是很明白，还请您指教。
1、deep与FM共享权重，具体是指的哪啊？在代码中体现在哪里？FM层初始化了一个权重w(这是一阶需要的是吗)？
2、Fm计算公式中，一阶和二阶计算都没有和输入x相乘是为什么啊？

**Comment by ZiyaoGeng** [comment]
1、共享权重是FM的二阶Embedding；
2、参考https://github.com/ZiyaoGeng/Recommender-System-with-TF2.0/issues/42
